import type { SourceRef } from "../domain/types";

export const sourceRegistry: SourceRef[] = [
  {
    id: "user-tree-full-a",
    kind: "userScreenshot",
    label: "User-provided Random Dice 2 full-tree screenshot A",
    observedAt: "2026-08-15",
    notes: "Primary topology, family-direction, visible rank, resource, and cost reference.",
  },
  {
    id: "user-tree-full-b",
    kind: "userScreenshot",
    label: "User-provided Random Dice 2 full-tree screenshot B",
    observedAt: "2026-08-15",
    notes: "Secondary topology reference showing the same central graph at a different viewport.",
  },
  {
    id: "user-prior-stat-details",
    kind: "userScreenshot",
    label: "Earlier user-provided Random Dice 2 stat detail screenshots",
    observedAt: "2026-08-15",
    notes: "Confirms specific next-rank values discussed in this conversation: global bullet damage and Chaos attack speed.",
  },
  {
    id: "user-node-detail-reference",
    kind: "userScreenshot",
    label: "User-provided tree detail UI reference",
    observedAt: "2026-08-15",
    notes: "Confirms the game uses node rank, next effect, prerequisite, and acquisition-state detail fields.",
  },
  {
    id: "appstore-rd2-2026",
    kind: "official",
    label: "Random Dice 2 — Apple App Store",
    url: "https://apps.apple.com/kr/app/random-dice-2/id6748432502",
    observedAt: "2026-08-15",
    notes: "111% product description confirming the custom growth-path progression concept; it does not publish a Dice Tree rank-cost table.",
  },
  {
    id: "googleplay-rd2-2026",
    kind: "official",
    label: "Random Dice 2 — Google Play",
    url: "https://play.google.com/store/apps/details?id=com.percent.aos.randomdice2",
    observedAt: "2026-08-15",
    notes: "111% current product listing confirming strategy-focused custom growth paths; no public node-cost ladder is provided.",
  },
  {
    id: "community-dc-engineering-317",
    kind: "community",
    label: "Random Dice 2 community lead: Engineering tree share",
    url: "https://m.dcinside.com/board/randomdice2/317",
    observedAt: "2026-08-15",
    notes: "Current-game community lead retained for manual cross-checking. Numerical claims are not promoted unless reverified.",
  },
  {
    id: "community-dc-devour-653",
    kind: "community",
    label: "Random Dice 2 community lead: Devour operation",
    url: "https://m.dcinside.com/board/randomdice2/653",
    observedAt: "2026-08-15",
    notes: "Current-game community strategy lead, not an official rules source.",
  },
  {
    id: "community-dc-f2p-1517",
    kind: "community",
    label: "Random Dice 2 community lead: early resource-efficient route",
    url: "https://m.dcinside.com/board/randomdice2/1517",
    observedAt: "2026-08-15",
    notes: "Current-game community strategy lead, not an official rules source.",
  },
  {
    id: "community-dc-devour-taeguk-643",
    kind: "community",
    label: "Random Dice 2 community lead: Devour vs Taeguk",
    url: "https://m.dcinside.com/board/randomdice2/643",
    observedAt: "2026-08-15",
    notes: "Comparison lead. Strategy opinions stay separate from canonical game facts.",
  },
  {
    id: "community-dc-near-full-tree-1515",
    kind: "community",
    label: "Random Dice 2 community lead: near-full Dice Tree",
    url: "https://m.dcinside.com/board/randomdice2/1515",
    observedAt: "2026-08-15",
    notes: "High-value geometry/data lead. Automated retrieval remains unreliable, so values require an actually retrieved current-game capture before promotion.",
  },
  {
    id: "community-dc-magic-496",
    kind: "community",
    label: "Random Dice 2 community lead: Magic tree data",
    url: "https://m.dcinside.com/board/randomdice2/496",
    observedAt: "2026-08-15",
    notes: "Magic branch research lead pending screenshot/text verification.",
  },
  {
    id: "community-dc-order-386",
    kind: "community",
    label: "Random Dice 2 community lead: Order route A",
    url: "https://m.dcinside.com/board/randomdice2/386",
    observedAt: "2026-08-15",
    notes: "Order branch research lead pending screenshot/text verification.",
  },
  {
    id: "community-dc-order-389",
    kind: "community",
    label: "Random Dice 2 community lead: Order route B",
    url: "https://m.dcinside.com/board/randomdice2/389",
    observedAt: "2026-08-15",
    notes: "Order branch research lead pending screenshot/text verification.",
  },
  {
    id: "community-dc-nature-380",
    kind: "community",
    label: "Random Dice 2 community lead: Nature tree",
    url: "https://m.dcinside.com/board/randomdice2/380",
    observedAt: "2026-08-15",
    notes: "Nature branch research lead pending screenshot/text verification.",
  },
];
