import { useEffect, useMemo, useState } from "react";
import { useI18n } from "../i18n/I18nContext";
import {
  cumulativeNodeCost, familyLabel, focusRecommendationIds, formatNumber,
  getDiceDefinition, getRuneDefinitionsForDice, getTreeNode, getTreeNodeForDice,
  nodeEffectText, rankCost, rd2Dice, rd2Source, rd2TreeNodes,
  type Locale, type RD2Family, type RD2TreeNode,
} from "../game-data/rd2Extracted";
import { simulateDiceStats } from "../simulator/diceSimulator";
import { ExactTreeCanvas } from "../features/tree/ExactTreeCanvas";

type Build = { schemaVersion:3; focusDiceType:string; ranks:Record<number,number>; inventory:{gold:number;nodeStone:number}; level:number; powerUp:number };
const FAMILY_ORDER: RD2Family[] = ["nature","order","chaos","engineering","magic"];
const fresh = (): Build => ({schemaVersion:3,focusDiceType:"Predator",ranks:{},inventory:{gold:0,nodeStone:0},level:1,powerUp:1});

function encodeBuild(build:Build){const bytes=new TextEncoder().encode(JSON.stringify(build));let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return `v3.${btoa(binary).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}`}
function decodeBuild(value:string):Build|null{try{if(!value.startsWith("v3."))return null;let e=value.slice(3).replaceAll("-","+").replaceAll("_","/");while(e.length%4)e+="=";const parsed=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(e),c=>c.charCodeAt(0)))) as Partial<Build>;if(parsed.schemaVersion!==3||typeof parsed.focusDiceType!=="string"||!parsed.ranks)return null;getDiceDefinition(parsed.focusDiceType);const ranks:Record<number,number>={};for(const [id,r] of Object.entries(parsed.ranks)){const node=getTreeNode(Number(id));if(node){const rank=Math.max(0,Math.min(node.maxRank,Math.floor(Number(r)||0)));if(rank)ranks[node.id]=rank}}return {...fresh(),...parsed,ranks,inventory:{gold:Math.max(0,Number(parsed.inventory?.gold)||0),nodeStone:Math.max(0,Number(parsed.inventory?.nodeStone)||0)},level:Math.max(1,Math.min(7,Number(parsed.level)||1)),powerUp:Math.max(1,Math.min(20,Number(parsed.powerUp)||1))}}catch{return null}}
function spentFor(ranks:Record<number,number>){let gold=0,nodeStone=0;for(const [id,r] of Object.entries(ranks)){const n=getTreeNode(Number(id));if(!n)continue;const c=cumulativeNodeCost(n,r);gold+=c.gold;nodeStone+=c.nodeStone}return{gold,nodeStone}}
function costText(cost:{gold:number;nodeStone:number},locale:Locale){const p=[] as string[];if(cost.gold)p.push(`${formatNumber(cost.gold)} ${locale==="ko"?"골드":"Gold"}`);if(cost.nodeStone)p.push(`${cost.nodeStone} ${locale==="ko"?"다이스 코어":"Dice Core"}`);return p.join(" · ")||(locale==="ko"?"비용 없음":"No cost")}
function nodeType(node:RD2TreeNode,locale:Locale){return ({DICE:{ko:"주사위 해금",en:"Dice unlock"},DICE_RUNE:{ko:"전용 효과",en:"Exclusive effect"},PLAYER_PASSIVE:{ko:"패시브",en:"Passive"},PERK:{ko:"계열 특성",en:"Family perk"}} as const)[node.nodeType][locale]}
function Stat({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="sim-stat-card"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}

export function App(){
 const {locale,setLocale}=useI18n();
 const [build,setBuild]=useState<Build>(fresh);
 const [selectedId,setSelectedId]=useState(5007);
 const [family,setFamily]=useState<RD2Family|"all">("all");
 const [query,setQuery]=useState("");
 const [shareUrl,setShareUrl]=useState("");
 const [shareOpen,setShareOpen]=useState(false);
 const [shareWarning,setShareWarning]=useState(false);
 useEffect(()=>{if(!location.hash.startsWith("#b="))return;const b=decodeBuild(decodeURIComponent(location.hash.slice(3)));if(!b){setShareWarning(true);return}setBuild(b);const n=getTreeNodeForDice(b.focusDiceType);if(n)setSelectedId(n.id)},[]);
 const selected=getTreeNode(selectedId)??rd2TreeNodes[0];
 const rank=build.ranks[selected.id]??0;
 const spent=useMemo(()=>spentFor(build.ranks),[build.ranks]);
 const focusDice=getDiceDefinition(build.focusDiceType);
 const focusIds=useMemo(()=>focusRecommendationIds(build.focusDiceType),[build.focusDiceType]);
 const sim=useMemo(()=>simulateDiceStats(build.focusDiceType,{level:build.level,powerUp:build.powerUp,treeRanks:build.ranks}),[build]);
 const runes=useMemo(()=>getRuneDefinitionsForDice(build.focusDiceType),[build.focusDiceType]);
 const diceOptions=useMemo(()=>rd2Dice.filter(d=>d.use&&getTreeNodeForDice(d.type)).sort((a,b)=>a.name.ko.localeCompare(b.name.ko,"ko")),[]);
 const setRank=(node:RD2TreeNode,r:number)=>setBuild(cur=>{const ranks={...cur.ranks};const v=Math.max(0,Math.min(node.maxRank,r));if(v)ranks[node.id]=v;else delete ranks[node.id];return{...cur,ranks}});
 const chooseDice=(type:string)=>{const n=getTreeNodeForDice(type);setBuild(c=>({...c,focusDiceType:type}));if(n){setSelectedId(n.id);setFamily(n.family)}};
 const share=async()=>{const url=`${location.origin}${location.pathname}#b=${encodeURIComponent(encodeBuild(build))}`;setShareUrl(url);setShareOpen(true);try{await navigator.clipboard?.writeText(url)}catch{}};
 const nextRank=Math.min(selected.maxRank,rank+1),nextCost=rankCost(selected,nextRank),totalCost=cumulativeNodeCost(selected,rank);
 const focusName=focusDice.name[locale];
 return <div className="exact-app">
  <header className="exact-header"><div className="brand"><span className="logo-die">RD²</span><div><strong>Dice Tree Lab</strong><small>Random Dice 2 · IPA table {rd2Source.tableBundleVersion}</small></div></div><div className="header-actions"><button onClick={()=>setLocale(locale==="ko"?"en":"ko")}>{locale==="ko"?"EN":"KO"}</button><button data-testid="share-button" className="primary" onClick={share}>{locale==="ko"?"빌드 공유":"Share build"}</button></div></header>
  {shareWarning&&<div data-testid="share-warning" className="warning">{locale==="ko"?"공유 링크를 읽을 수 없어 새 빌드를 열었습니다.":"The shared build could not be read."}<button onClick={()=>setShareWarning(false)}>×</button></div>}
  <section className="focus-bar"><div><span>{locale==="ko"?"목표 주사위":"Focus dice"}</span><strong>{focusName}</strong><small>{familyLabel(focusDice.family as RD2Family,locale)} · {focusDice.description[locale]}</small></div><div className="quick-dice">{["Predator","Decay","Bingo"].map(type=>{const d=getDiceDefinition(type);return <button key={type} aria-label={d.name[locale]} className={build.focusDiceType===type?"active":""} onClick={()=>chooseDice(type)}>{d.name[locale]}<small>{familyLabel(d.family as RD2Family,locale)}</small></button>})}</div><label className="dice-select"><span>{locale==="ko"?"전체 주사위":"All dice"}</span><select value={build.focusDiceType} onChange={e=>chooseDice(e.target.value)}>{diceOptions.map(d=><option key={d.type} value={d.type}>{d.name[locale]}</option>)}</select></label></section>
  <section className="currency-bar" data-testid="resource-summary"><div className="currency-title"><span>{locale==="ko"?"다이스 트리 재화":"Dice Tree currency"}</span><strong>239 {locale==="ko"?"노드":"nodes"}</strong></div><label><b className="coin">G</b><span>{locale==="ko"?"골드":"Gold"}</span><input aria-label={locale==="ko"?"보유 골드":"Gold inventory"} type="number" min="0" value={build.inventory.gold} onChange={e=>setBuild(c=>({...c,inventory:{...c.inventory,gold:Math.max(0,Number(e.target.value)||0)}}))}/><em>−{formatNumber(spent.gold)}</em></label><label><b className="core">C</b><span>{locale==="ko"?"다이스 코어":"Dice Core"}</span><input aria-label={locale==="ko"?"보유 다이스 코어":"Dice Core inventory"} type="number" min="0" value={build.inventory.nodeStone} onChange={e=>setBuild(c=>({...c,inventory:{...c.inventory,nodeStone:Math.max(0,Number(e.target.value)||0)}}))}/><em>−{formatNumber(spent.nodeStone)}</em></label><div className="source-chip"><span>IPA 1.0.1</span><strong>{rd2Source.tableCreatedAt.slice(0,10)}</strong></div></section>
  <main className="exact-workspace"><section className="tree-area"><div className="tree-toolbar"><div className="family-tabs"><button className={family==="all"?"active":""} onClick={()=>setFamily("all")}>{locale==="ko"?"전체":"All"}</button>{FAMILY_ORDER.map(f=><button key={f} className={family===f?"active":""} onClick={()=>setFamily(f)}>{familyLabel(f,locale)}</button>)}</div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==="ko"?"주사위·효과 검색":"Search dice & effects"}/></label></div><div className="tree-card"><div className="tree-note"><strong>{locale==="ko"?"인게임 좌표·연결":"In-game coordinates & links"}</strong><span>{locale==="ko"?"239개 노드를 원본 DiceTreeNodeTable로 렌더링":"Rendered from DiceTreeNodeTable"}</span></div><ExactTreeCanvas nodes={rd2TreeNodes} locale={locale} selectedNodeId={selectedId} plannedRanks={build.ranks} focusIds={focusIds} query={query} familyFilter={family} onSelect={setSelectedId}/></div></section>
   <aside className="side-panel"><section className="node-panel" data-testid="node-panel"><div className="eyebrow"><span>{familyLabel(selected.family,locale)}</span><small>{nodeType(selected,locale)}</small></div><div className="node-title"><div className={`node-avatar family-${selected.family}`}>{selected.nodeType==="DICE"?selected.name.ko.replace(" 주사위","").slice(0,2):selected.nodeType==="DICE_RUNE"?"◆":"↑"}</div><div><h2>{selected.name[locale]}</h2><p>Node #{selected.id} · ({selected.position.x}, {selected.position.y})</p></div></div><div className="effect"><span>{locale==="ko"?"효과":"Effect"}</span><strong>{nodeEffectText(selected,Math.max(1,rank||1),locale)||selected.name[locale]}</strong></div><div className="rank-head"><span>{locale==="ko"?"가상 랭크":"Planned rank"}</span><strong>{rank} / {selected.maxRank}</strong></div><div className="rank-control"><button aria-label="rank down" disabled={!rank} onClick={()=>setRank(selected,rank-1)}>−</button><input aria-label={locale==="ko"?"노드 랭크":"Node rank"} type="range" min="0" max={selected.maxRank} value={rank} onChange={e=>setRank(selected,Number(e.target.value))}/><button aria-label="rank up" disabled={rank>=selected.maxRank} onClick={()=>setRank(selected,rank+1)}>+</button></div><div className="cost-grid"><div><span>{locale==="ko"?"누적 비용":"Total cost"}</span><strong>{costText(totalCost,locale)}</strong></div><div><span>{rank>=selected.maxRank?"MAX":`${locale==="ko"?"다음 랭크":"Next rank"} ${nextRank}`}</span><strong>{rank>=selected.maxRank?"MAX":costText(nextCost,locale)}</strong></div></div><button className="max-btn" onClick={()=>setRank(selected,selected.maxRank)}>{locale==="ko"?"MAX 미리보기":"Preview MAX"}</button></section>
    <section className="sim-panel"><div className="sim-heading"><div><small>DefenderTable + ProjectileAbilityTable</small><h2>{locale==="ko"?`${focusDice.name.ko.replace(" 주사위","")} 시뮬레이터`:`${focusDice.name.en} simulator`}</h2></div><span>{familyLabel(focusDice.family as RD2Family,locale)}</span></div><div className="sliders"><label><span>{locale==="ko"?"눈금 레벨":"Dot level"} <b>{build.level}</b></span><input type="range" min="1" max="7" value={build.level} onChange={e=>setBuild(c=>({...c,level:Number(e.target.value)}))}/></label><label><span>{locale==="ko"?"파워업":"Power-Up"} <b>{build.powerUp}</b></span><input type="range" min="1" max="20" value={build.powerUp} onChange={e=>setBuild(c=>({...c,powerUp:Number(e.target.value)}))}/></label></div><div className="stat-grid"><Stat label={locale==="ko"?"기본 대미지":"Base DMG"} value={formatNumber(sim.attack)}/><Stat label={locale==="ko"?"공격 주기":"ATK interval"} value={`${sim.attackInterval.toFixed(2)}s`} sub={`${sim.attacksPerSecond.toFixed(3)}/s`}/><Stat label={locale==="ko"?"사거리":"Range"} value={sim.range.toFixed(2)}/><Stat label={locale==="ko"?"보스 대미지":"Boss DMG"} value={`${formatNumber(sim.bossDamagePercent)}%`}/></div>{sim.projectileAbility&&<div className="ability"><span>{sim.projectileAbility.label[locale]|| (locale==="ko"?"고유 수치":"Ability")}</span><strong>{formatNumber(sim.projectileAbility.value)}</strong>{build.level===7&&focusDice.level7Description[locale]&&<p>{focusDice.level7Description[locale]}</p>}</div>}<div className="bonus-grid"><div><span>{locale==="ko"?"트리 불렛 대미지":"Tree Bullet DMG"}</span><strong>+{formatNumber(sim.treeBonuses.bulletDamagePercent)}%</strong></div><div><span>{locale==="ko"?"트리 공격속도":"Tree ATK SPD"}</span><strong>+{formatNumber(sim.treeBonuses.attackSpeedPercent)}%</strong></div><div><span>{locale==="ko"?"예상 불렛 DPS":"Projected bullet DPS"}</span><strong>{formatNumber(sim.projectedBulletDps)}</strong></div></div><p className="model-note">{locale==="ko"?"기본·눈금·파워업 수치는 IPA 테이블 원본이며, DPS는 트리에 명시된 불렛 대미지/공격속도 %를 적용한 시뮬레이션입니다.":"Base/dot/Power-Up values come from the extracted tables. DPS is a planner projection using displayed tree percentages."}</p><div className="runes"><h3>{locale==="ko"?"전용 효과":"Exclusive effects"}</h3>{runes.map(r=>{const n=rd2TreeNodes.find(x=>x.nodeType==="DICE_RUNE"&&x.kindId===r.id);if(!n)return null;const rr=build.ranks[n.id]??0;return <button key={r.id} onClick={()=>setSelectedId(n.id)}><span>◆</span><div><strong>{r.name[locale]}</strong><small>{nodeEffectText(n,Math.max(1,rr||1),locale)}</small></div><em>{rr}/{n.maxRank}</em></button>})}</div></section>
   </aside></main>
  {shareOpen&&<div className="share-modal" data-testid="share-popover" onMouseDown={e=>{if(e.target===e.currentTarget)setShareOpen(false)}}><section><header><div><small>{locale==="ko"?"로그인 없이 공유":"No-login share"}</small><h2>{locale==="ko"?"현재 빌드 링크":"Current build link"}</h2></div><button onClick={()=>setShareOpen(false)}>×</button></header><p>{locale==="ko"?"목표 주사위, 가상 랭크, 재화, 눈금과 파워업 상태가 URL에 저장됩니다.":"Focus dice, ranks, currency, dot level and Power-Up are encoded in the URL."}</p><input data-testid="share-url" readOnly value={shareUrl}/></section></div>}
 </div>
}
